name: OWM Client CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  validate:
    env:
      OWM_TOKEN: ${{ secrets.OWM_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Validate
      uses: curium-rocks/actions/validate-node@main
      with:
        node_version: 16.x
        github_token: ${{ secrets.GITHUB_TOKEN }}
        sonarqube_token: ${{ secrets.SONARQUBE_KEY }}
  publish:
    needs: validate
    environment: github-pages
    permissions:
      pages: write
      id-token: write
      contents: write
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Publish
      uses: curium-rocks/actions/publish-node@main
      with:
        node_version: 16.x
        npm_token: ${{ secrets.NODE_ACCESS_TOKEN }}
        user_name: 'ci'
        user_email: 'git@curium.rocks'
        publish_docs: 'true'
        create_release: 'true'
        token: ${{ secrets.github_token }}
